package repositories;

import java.sql.Connection;
import java.sql.SQLException;


import mappers.IMapResultSetToEntity;
import domain.Entity;
import domain.User;

public class UserRepository extends RepositoryBase<User> {
		
	
	public UserRepository(Connection connection, IMapResultSetToEntity<User> mapper) {
		super(connection,mapper);
	}
	
	public void setInsertQuery(User u) throws SQLException {
		insert.setString(1, u.getLogin());
		insert.setString(2, u.getPassword());
		insert.setString(3, u.getEmail());
		
	}
	
	public void setUpdateQuery(User u) throws SQLException {
		update.setInt(1,  u.getId());
		
	}
	
	protected String tableName(){
		return "user";
	}

	protected String createTableSql(){
		return "CREATE TABLE user("
				+"id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+"Login VARCHAR(20)," 
				+"Password VARCHAR(20),"
				+"Email VARCHAR(30),"
				+"Type VARCHAR(20) DEFAULT 'Normal');";
		
	}
	
	protected String insertSql(){
		return "INSERT INTO user(Login, Password, Email) VALUES (?,?,?)";
	}
	
	protected String updateSql(){
		return "UPDATE user SET Type = 'premium' WHERE id = ?";
	}

}
